### ISSUE TITLE
Integer Overflow in BZip2 Decode

### ISSUE THREAD

**Issue by elihwyma** [tsolomko/SWCompression#21]
`Swift runtime failure: arithmetic overflow`
Line 214 of BZip2.swift

The Packages file causing issues can be downloaded [here](https://d7my-dev.github.io/repo/Packages.bz2)

**Comment by tsolomko** [comment]
Thank you for your report.

I fixed this issue, the fix will be released in 4.5.9.

I have one question though. The issue is related to this statement from [wikipedia](https://en.wikipedia.org/wiki/Bzip2): "While the specification theoretically allows for runs of length 256–259 to be encoded, the reference encoder will not produce such output". The implementation in SWCompression relied on this assumption that run lengths will be only up to 255, which the file you provided proves to be incorrect.

So I am curious: do you know by any chance what program was used to produce (compress) this file?

**Comment by elihwyma** [comment]
Thanks for the fix 

I have no idea what was used to create it. It came from an APT repo
