### ISSUE TITLE
Does your library currently support ios9

### ISSUE THREAD

**Issue by yuanjunxiao** [tsolomko/SWCompression#5]
Ask a question。Does your library currently support ios9?

**Comment by tsolomko** [comment]
While I haven't checked, I think that it should support ios9.

**Comment by yuanjunxiao** [comment]
It crashed when I was using ios9.3.5. Under the ZLib/ zlibarchive.swift file, this line of code has an issue else {throw ZlibError. WrongAdler32 (out)}. But when I'm running on an ios10+ app, that's fine. I hope you can see why.

**Comment by tsolomko** [comment]
Hmm, I am unable to reproduce the issue you are talking about: I downloaded ios 9.3 simulator and run my tests using it and I haven't encountered any crashes. What version of Swift are you using? Is it possible for you to provide a zlib archive file that is causing the crash?

**Comment by tsolomko** [comment]
I guess, I should have also asked: what version of SWCompression are you using?

**Comment by yuanjunxiao** [comment]
'SWCompression', '~> 4.5.0'  I am a real ios9.3.5 crash

**Comment by tsolomko** [comment]
What about my other questions:
- What version of Swift are you using?
- Is it possible for you to provide a zlib archive file that is causing the crash?

**Comment by yuanjunxiao** [comment]
We are using Swift3.0 and currently intend to upgrade to 4.2. Let's check first. Update and see if there are any problems. Thank you very much for your reply

**Comment by yuanjunxiao** [comment]
Hello, I updated the latest version of SWCompression today, but it will still crash in ios9.3.5 system. My breakpoint is located here.ZLib / zlibarchive.swift
let adler32 = bitReader.uint32().byteSwapped
        guard CheckSums.adler32(out) == adler32
            else { throw ZlibError.wrongAdler32(out) }
malloc: *** malloc_zone_unregister() failed for 0x68ec000
==5290==__sanitizer_mz_destroy() called -- ignoring
I think this library (BiByteData) compatibility is not good.Can you test optimize it?

**Comment by tsolomko** [comment]
Hi, sorry for the long response time.

I am still unable to reproduce your issue. As far I understand, you encounter this problem when using Swift 3 and iOS 9, and while SWCompression does support iOS 9.0 (simply because no iOS-specific APIs are used), Swift 3 is NOT supported by SWCompression starting with its 4.0 release. Frankly, I am quite surprised that you were even able to compile SWCompression with Swift 3 in the first place. 

Additionally, I can't really investigate this problem without the zlib data/file that is causing it. If I understand correctly, you are trying to read/open data that is archived with zlib and then you encounter this crash. It would be extremely helpful if you could provide me an example of zlib-compressed data that causes SWCompression to crash.

Thank you.
