### ISSUE TITLE
Can't add package dependency in Xcode 11.4

### ISSUE THREAD

**Issue by jkinder61** [tsolomko/SWCompression#9]
It appears the lfs issue is still there.

**Comment by tsolomko** [comment]
Hi,

I am sorry hear that you are still having issues. Could you please more specific what kind of problem you're experiencing? Since I am personally unable to use (or even install) Xcode 11.4 (or, in fact, any Xcode newer than 10.1), could you please provide as many details as possible?

**Comment by jkinder61** [comment]
Hi Timofey,

Not sure how much good this will do, if you can’t install Xcode 11, but here are more details below.

At first, I was getting an error complaining that lfs was not a git command.  

After installing home-brew and las, I still couldn’t add your project.  I got the following error.

Regards,
JK



Showing All Messages
: terminated(1): SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS=/Users/username/Library/WebKit/Databases PATH=/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin GIT_SSH_COMMAND=ssh -oBatchMode=yes CA_DEBUG_TRANSACTIONS=1 XPC_SERVICE_NAME=com.apple.dt.Xcode.3868 MallocNanoZone=0 XPC_FLAGS=0x0 __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0 GIT_TERMINAL_PROMPT=0 USER= username TMPDIR=/var/folders/9f/46_hxx110b76xk2mbhvlhfnh0000gn/T/ CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 SHELL=/bin/zsh HOME=/Users/username LOGNAME= username SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.IoTHSR9Ugz/Listeners /Applications/Xcode.app/Contents/Developer/usr/bin/git -C /Users/username/Library/Developer/Xcode/DerivedData/Project-fygytinbttozjhfhaykvjqvdjmxz/SourcePackages/checkouts/SWCompression submodule update --init --recursive output:
    Submodule 'Tests/Test Files' (https://github.com/tsolomko/SWCompression-Test-Files.git) registered for path 'Tests/Test Files'
    Cloning into '/Users/username/Library/Developer/Xcode/DerivedData/Project-fygytinbttozjhfhaykvjqvdjmxz/SourcePackages/checkouts/SWCompression/Tests/Test Files'...
    git-lfs filter-process: git-lfs: command not found
    fatal: the remote end hung up unexpectedly
    Unable to checkout '543e5bc90d065c9cac22e501cff97d5c4489ce45' in submodule path 'Tests/Test Files'

**Comment by tsolomko** [comment]
Just curious, after installing git-lfs using homebrew, did you run `git lfs install` or `git lfs install --system`?

**Comment by tsolomko** [comment]
Also, do you have git installed using homebrew as well? Or are you using the one from Xcode Command Line Tools?

**Comment by jkinder61** [comment]
I believe I did, but I’m not sure.

**Comment by tsolomko** [comment]
Anyway, I think I now understand why this happens. Basically, by installing git-lfs and running the aforementioned commands you specified in global/system git config that you have git-lfs installed and it should be used. When Xcode is using git it reads global/system git config and tries to use git-lfs (because of it's used in SWCompression's repository), but in Xcode's PATH environment variable there is no git-lfs, and thus it fails.

As a workaround I would like to suggest (if you don't need git-lfs for any of your other projects) to run in the Terminal the following commands:
```bash
git lfs uninstall
sudo git lfs uninstall --system
```
Then, if you don't need it, you can remove git-lfs itself (`brew rm git-lfs`).

Please let me know if this helps. Meanwhile, I will work on a more permanent solution on my side: I have some ideas, but it will take some time to implement them.

**Comment by tsolomko** [comment]
I've released today an update to SWCompression (4.5.4), which should fix this issue.

**Comment by jkinder61** [comment]
Thank you.
